# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
description: > # this means to ignore newlines until "baseurl:"
        This is my personal open lab notebook as part of a research project done at TTU starting in Fall 2016 under the supervision of Dr. Thomas Maccarone.
baseurl: "/VIMOSlabbook"
gems:
  - jekyll-pandoc
  - jekyll-archives

jekyll-archives:
  enabled: [categories,tags]
  layout: 'tag_page'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name.html'

tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: Pandoc
highlighter: pygments
pandoc:
  extensions: 
    - smart
    - mathjax
    - bibliography: bibliography/labnotebook.bib

author:
  name: Manuel Pichardo marcano
  givenName: Manuel
  familyName: Pichardo M
  github: manuelmarcano22
title: Lab Notebook for VIMOS Data Reduction starting Fall 2016 TTU
name: Lab Notebook for VIMOS Data Reduction starting Fall 2016 TTU
email: manuel.pichardo-marcano@ttu.edu
